### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Sxx1995** [batra-mlp-lab/visdial-rl#14]
I ran the command "python train.py -useGPU -trainMode sl-abot". However, I got such error "RuntimeError: CUDA error: out of memory". How much GPU memory is needed when training the model? The memory of my GPU is 12212MiB. Thanks!

**Comment by Jiaqiang-Ruan** [comment]
Hi, I encountered the same problem. Is the problem solved?

**Comment by sinhprous** [comment]
please wrap the `rankABot` calling (https://github.com/batra-mlp-lab/visdial-rl/blob/master/train.py#L409) with `with torch.no_grad():`
